### ISSUE TITLE
能不能出个傻瓜点的安装教程，

### ISSUE THREAD

**Issue by wanfeng803** [messoer/react-music#5]
弄了半天还是没有成功。。。。谢谢
网页版和app版是如何操作的呢

**Comment by theShapeOfvoice** [comment]
你好，这个只是网页版本的呢，没有app版本，安装的话，你把项目clone下来，安装好开发环境(node,yarn等），执行安装命令(yarn install)下载依赖的包，然后执行npm run start运行就可以了
